### ISSUE TITLE
AMDS-Amptek Change Trigger Dwell to use AMDS-Scaler Style Communication

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#126] opened 2015-12-23 17:08 UTC
The AMDS-Scaler uses a much clearer algorithm to generate trigger/dwell data. The AMDS-Amptek code needs to be updated to move to this paradigm and remove a lot of unnecessary code in both the AmptekSDD123 classes and AMDSBufferGroup.

**Comment by XuetaoLiu-S** [comment] 2016-01-05 19:16
Time Estimate: 2 hours

@davidChevrier you might want to add your time for this as well.

**Comment by dretrex** [comment] 2016-01-05 19:19
If the issue is in pull request you can probably close this issue now too.

**Closed as completed** 2016-01-05 19:36 UTC
